using System.IO;
using Cove.Persistence;
using Cove.Platform;
using Microsoft.Extensions.Logging;

namespace Cove.Engine.Shell;

public sealed class ManagedShellService
{
    private readonly string _dataDir;
    private readonly ILogger _logger;
    private readonly string _cliPath;

    public ManagedShellService(string dataDir, string cliPath, ILogger logger)
    {
        _dataDir = dataDir;
        _cliPath = cliPath;
        _logger = logger;
    }

    public string EnvShPath => Path.Combine(_dataDir, "env.sh");
    public string EnvFishPath => Path.Combine(_dataDir, "env.fish");
    public string BinCovePath => Path.Combine(_dataDir, "bin", "cove");

    public void GenerateEnvSh()
    {
        var dir = Path.GetDirectoryName(EnvShPath)!;
        Directory.CreateDirectory(dir);
        AtomicJsonStore.WriteRawText(EnvShPath, GeneratePosixContent());
        AtomicJsonStore.WriteRawText(EnvFishPath, GenerateFishContent());
    }

    private string GeneratePosixContent()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Cove managed shell environment (POSIX: bash/zsh)");
        sb.AppendLine("# Generated by cove. Do not edit by hand.");
        sb.AppendLine($"export COVE_DATA_DIR=\"{_dataDir}\"");
        sb.AppendLine($"export COVE_CLI_PATH=\"{_cliPath}\"");
        sb.AppendLine($"export __COVE_MANAGED_KEYS=\"COVE_DATA_DIR:COVE_CLI_PATH\"");
        sb.AppendLine();
        sb.AppendLine("# PATH addition (idempotent)");
        sb.AppendLine("_cove_bin=\"$(dirname \"$COVE_CLI_PATH\")\"");
        sb.AppendLine("case \":$PATH:\" in");
        sb.AppendLine("  *\":$_cove_bin:\"*) ;;");
        sb.AppendLine("  *) export PATH=\"$_cove_bin:$PATH\" ;;");
        sb.AppendLine("esac");
        return sb.ToString();
    }

    private string GenerateFishContent()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Cove managed shell environment (fish)");
        sb.AppendLine("# Generated by cove. Do not edit by hand.");
        sb.AppendLine($"set -x COVE_DATA_DIR \"{_dataDir}\"");
        sb.AppendLine($"set -x COVE_CLI_PATH \"{_cliPath}\"");
        sb.AppendLine($"set -x __COVE_MANAGED_KEYS \"COVE_DATA_DIR:COVE_CLI_PATH\"");
        sb.AppendLine();
        sb.AppendLine("# PATH addition (idempotent)");
        sb.AppendLine("set -l _cove_bin (dirname \"$COVE_CLI_PATH\")");
        sb.AppendLine("if not contains -- \"$_cove_bin\" $PATH");
        sb.AppendLine("  set -x PATH \"$_cove_bin\" $PATH");
        sb.AppendLine("end");
        return sb.ToString();
    }

    public void ReinstallBinCove()
    {
        var binDir = Path.Combine(_dataDir, "bin");
        Directory.CreateDirectory(binDir);
        var needsReinstall = !File.Exists(BinCovePath) || VersionMismatch();
        if (!needsReinstall)
            return;
        if (!File.Exists(_cliPath))
        {
            _logger.ManagedShellCliMissing(_cliPath);
            return;
        }
        var tempPath = Path.Combine(binDir, $".cove.tmp-{System.Guid.NewGuid():N}");
        File.Copy(_cliPath, tempPath, overwrite: true);
        SetExecutable(tempPath);
        try
        {
            File.Move(tempPath, BinCovePath, overwrite: true);
        }
        catch (IOException ex)
        {
            _logger.ManagedShellReinstallFailed(BinCovePath, ex.Message);
            try { File.Delete(tempPath); } catch { }
            return;
        }
        File.WriteAllText(Path.Combine(binDir, ".cove-version"), CoveBuild.InformationalVersion);
    }

    private bool VersionMismatch()
    {
        var versionPath = Path.Combine(_dataDir, "bin", ".cove-version");
        if (!File.Exists(versionPath))
            return true;
        var installed = File.ReadAllText(versionPath).Trim();
        return installed != CoveBuild.InformationalVersion;
    }

    private void SetExecutable(string path)
    {
        if (OperatingSystem.IsWindows())
            return;
        try
        {
            File.SetUnixFileMode(path, System.IO.UnixFileMode.UserRead | System.IO.UnixFileMode.UserWrite | System.IO.UnixFileMode.UserExecute | System.IO.UnixFileMode.GroupRead | System.IO.UnixFileMode.GroupExecute | System.IO.UnixFileMode.OtherRead | System.IO.UnixFileMode.OtherExecute);
        }
        catch (IOException ex)
        {
            _logger.ManagedShellChmodFailed(path, ex.Message);
        }
    }
}
