using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Cove.SourceGen;

[Generator(LanguageNames.CSharp)]
public sealed class CoveCommandGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Cove.Protocol.CoveCommandAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commands = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) => Extract(ctx))
            .Where(static c => c.Key != null);

        var collected = commands.Collect();
        context.RegisterSourceOutput(collected, static (spc, items) => Emit(spc, items));
    }

    private static CommandModel Extract(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not IMethodSymbol method) return default;
        if (!method.IsStatic) return default;
        if (method.Parameters.Length != 1) return default;
        var attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length < 1) return default;
        var key = attr.ConstructorArguments[0].Value as string;
        if (key is null || key.Length == 0) return default;
        var containing = method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var paramType = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return new CommandModel(key, containing, method.Name, paramType, returnType);
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<CommandModel> items)
    {
        var ordered = items.Where(x => x.Key != null).OrderBy(x => x.Key, System.StringComparer.Ordinal).ToArray();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Cove.Generated;");
        sb.AppendLine("internal static class CoveCommandRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly System.Collections.Generic.IReadOnlyDictionary<string, System.Delegate> Handlers =");
        sb.AppendLine("        new System.Collections.Generic.Dictionary<string, System.Delegate>(System.StringComparer.Ordinal)");
        sb.AppendLine("        {");
        foreach (var c in ordered)
            sb.AppendLine($"            [\"{c.Key}\"] = (System.Func<{c.ParamType}, {c.ReturnType}>){c.ContainingType}.{c.MethodName},");
        sb.AppendLine("        };");
        sb.Append("    public static readonly System.Collections.Generic.IReadOnlyList<string> Keys = new string[] { ");
        foreach (var c in ordered) sb.Append($"\"{c.Key}\", ");
        sb.AppendLine("};");
        sb.AppendLine("}");
        spc.AddSource("CoveCommandRegistry.g.cs", sb.ToString());
    }

    private readonly struct CommandModel
    {
        public readonly string Key;
        public readonly string ContainingType;
        public readonly string MethodName;
        public readonly string ParamType;
        public readonly string ReturnType;
        public CommandModel(string key, string containingType, string methodName, string paramType, string returnType)
        {
            Key = key;
            ContainingType = containingType;
            MethodName = methodName;
            ParamType = paramType;
            ReturnType = returnType;
        }
    }
}
