using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Cove.SourceGen;

[Generator(LanguageNames.CSharp)]
public sealed class SettingSchemaGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Cove.Engine.Config.SettingAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var settings = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is PropertyDeclarationSyntax,
                transform: static (ctx, _) => Extract(ctx))
            .Where(static s => s.Label != null);

        var collected = settings.Collect();
        context.RegisterSourceOutput(collected, static (spc, items) => Emit(spc, items));
    }

    private static SettingModel Extract(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not IPropertySymbol prop) return default;
        var attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length < 2) return default;
        var label = attr.ConstructorArguments[0].Value as string;
        var tab = attr.ConstructorArguments[1].Value as string;
        var control = attr.ConstructorArguments.Length >= 3 ? attr.ConstructorArguments[2].Value as string ?? "text" : "text";
        string? description = null;
        string[]? options = null;
        foreach (var na in attr.NamedArguments)
        {
            if (na.Key == "Description" && na.Value.Value is string d) description = d;
            if (na.Key == "Options" && na.Value.Values is { } vals)
            {
                var list = new System.Collections.Generic.List<string>();
                foreach (var v in vals) if (v.Value is string s) list.Add(s);
                options = list.Count > 0 ? list.ToArray() : null;
            }
        }

        var containingType = prop.ContainingType;
        var sectionName = containingType.Name;
        var configKey = ResolveConfigKey(sectionName, prop.Name);

        var typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var typeShort = typeName switch
        {
            "string" => "string",
            "int" => "int",
            "double" => "double",
            "bool" => "bool",
            _ when typeName.StartsWith("System.Collections.Generic.Dictionary<") => "object",
            _ when typeName.StartsWith("System.Collections.Generic.List<") => "array",
            _ => "object"
        };

        return new SettingModel(configKey, label!, tab!, control, description, typeShort, options);
    }

    private static string ResolveConfigKey(string sectionName, string propertyName)
    {
        var sectionKey = sectionName switch
        {
            "CoveConfig" => null,
            "AppearanceSection" => "appearance",
            "TerminalSection" => "terminal",
            "MarkdownEditorSection" => "markdown_editor",
            "UpdatesSection" => "updates",
            "DiagnosticsSection" => "diagnostics",
            "WorktreeSection" => "worktree",
            "TelemetrySection" => "telemetry",
            "RemoteConfigSection" => "remoteConfig",
            "KeybindingsSection" => "keybindings",
            "PushToTalkSection" => "pushToTalk",
            "SpeechSection" => "speech",
            "LspServersSection" => "lspServers",
            "AdapterCommandsSection" => "adapterCommands",
            _ => sectionName
        };

        var propKey = CamelCase(propertyName);
        return sectionKey is null ? propKey : $"{sectionKey}.{propKey}";
    }

    private static string CamelCase(string s)
    {
        if (s.Length == 0) return s;
        return char.ToLowerInvariant(s[0]) + s.Substring(1);
    }
    private static void Emit(SourceProductionContext spc, ImmutableArray<SettingModel> items)
    {
        var ordered = items.Where(x => x.Label != null).OrderBy(x => x.Key, System.StringComparer.Ordinal).ToArray();
        if (ordered.Length == 0) return;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Cove.Generated;");
        sb.AppendLine();
        sb.AppendLine("public sealed record SettingSchemaEntry(string Key, string Label, string Tab, string Control, string? Description, string Type, string[]? Options);");
        sb.AppendLine();
        sb.AppendLine("public static class CoveSettingSchema");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly System.Collections.Generic.IReadOnlyList<SettingSchemaEntry> Entries = new SettingSchemaEntry[]");
        sb.AppendLine("    {");
        foreach (var s in ordered)
        {
            var optionsExpr = s.Options is null || s.Options.Length == 0
                ? "null"
                : "new string[] { " + string.Join(", ", s.Options.Select(o => $"\"{o}\"")) + " }";
            sb.AppendLine($"        new SettingSchemaEntry(\"{s.Key}\", \"{s.Label}\", \"{s.Tab}\", \"{s.Control}\", {(s.Description is null ? "null" : $"\"{s.Description}\"")}, \"{s.Type}\", {optionsExpr}),");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");
        spc.AddSource("CoveSettingSchema.g.cs", sb.ToString());
    }

    private readonly struct SettingModel
    {
        public readonly string Key;
        public readonly string Label;
        public readonly string Tab;
        public readonly string Control;
        public readonly string? Description;
        public readonly string Type;
        public readonly string[]? Options;
        public SettingModel(string key, string label, string tab, string control, string? description, string type, string[]? options = null)
        {
            Key = key; Label = label; Tab = tab; Control = control; Description = description; Type = type; Options = options;
        }
    }
}
